version: "3.8"
services:
  skybridge:
    container_name: "skybridge"
    image: videah/skybridge:latest
    restart: always
    volumes:
      - skybridge:/app/database
    environment:
      # Base URL of where SkyBridge will be hosted without the protocol.
      - SKYBRIDGE_BASEURL=jkeds-skybridge.fly.dev
      # Random secret, generate with `openssl rand -base64 32`.
      - SKYBRIDGE_SECRET=iO1dnnb9XDccq49+362/3gdhZTm2FtpbOp2grGu7K8M=
      # Password used to make a SkyBridge instance private.
      - SKYBRIDGE_AUTH_PASSWORD=z0eocAjYn2p4Or4Pm624FQ==
      # Should a bridge password be required to authenticate?
      - SKYBRIDGE_REQUIRE_AUTH_PASSWORD=true
      # Should a nice index page be shown on the root URL?
      - SKYBRIDGE_SHOW_INDEX=false
      # Allow backfilling/scrolling on timelines? (can cause issues on instances under heavy load)
      - SKYBRIDGE_ALLOW_BACKFILL=true

volumes:
  skybridge:
